/*
 * This JS Object stores all the tables names and its columns names.
 * This object can be used for visualizations and places where the name of the columns are needed.
 */

import { DefaultColumnFilter, SelectColumnFilter } from '../components/Filters/filters';

export const tableSchema = {
  patients: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'otherIds': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'dateOfBirth': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'gender': {'Filter': SelectColumnFilter, 'active': true, 'hidden': false},
    'ethnicity': {'Filter': SelectColumnFilter, 'active': true, 'hidden': false},
    'race': {'Filter': SelectColumnFilter, 'active': true, 'hidden': false},
    'provinceOfResidence': {'Filter': SelectColumnFilter, 'active': true, 'hidden': false},
    'dateOfDeath': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'causeOfDeath': {'Filter': SelectColumnFilter, 'active': true, 'hidden': false},
    'autopsyTissueForResearch': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'priorMalignancy': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'dateOfPriorMalignancy': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'familyHistoryAndRiskFactors': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'familyHistoryOfPredispositionSyndrome': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'detailsOfPredispositionSyndrome': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'geneticCancerSyndrome': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'otherGeneticConditionOrSignificantComorbidity': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'occupationalOrEnvironmentalExposure': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  enrollments: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'enrollmentInstitution': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'enrollmentApprovalDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'crossEnrollment': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'otherPersonalizedMedicineStudyName': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'otherPersonalizedMedicineStudyId': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'ageAtEnrollment': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'eligibilityCategory': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'statusAtEnrollment': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'primaryOncologistName': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'primaryOncologistContact': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'referringPhysicianName': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'referringPhysicianContact': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'summaryOfIdRequest': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'treatingCentreName': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'treatingCentreProvince': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
  },
  treatments: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'courseNumber': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'therapeuticModality': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'treatmentPlanType': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'treatmentIntent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'startDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'stopDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'reasonForEndingTheTreatment': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'responseToTreatment': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'responseCriteriaUsed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'dateOfRecurrenceOrProgressionAfterThisTreatment': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'unexpectedOrUnusualToxicityDuringTreatment': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  samples: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'sampleId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'diagnosisId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'localBiobankId': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'collectionDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'collectionHospital': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'sampleType': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'tissueDiseaseState': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'anatomicSiteTheSampleObtainedFrom': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'cancerType': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'cancerSubtype': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'pathologyReportId': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'morphologicalCode': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'topologicalCode': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'shippingDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'receivedDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'qualityControlPerformed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'estimatedTumorContent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'quantity': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'units': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'associatedBiobank': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'otherBiobank': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'sopFollowed': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'ifNotExplainAnyDeviation': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
  },
  diagnoses: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'diagnosisId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'diagnosisDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'ageAtDiagnosis': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'cancerType': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'classification': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'cancerSite': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'histology': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'methodOfDefinitiveDiagnosis': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'sampleType': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'sampleSite': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'tumorGrade': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'gradingSystemUsed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'sitesOfMetastases': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'stagingSystem': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'versionOrEditionOfTheStagingSystem': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'specificTumorStageAtDiagnosis': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'prognosticBiomarkers': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'biomarkerQuantification': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'additionalMolecularTesting': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'additionalTestType': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'laboratoryName': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'laboratoryAddress': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'siteOfMetastases': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'stagingSystemVersion': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'specificStage': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'cancerSpecificBiomarkers': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'additionalMolecularDiagnosticTestingPerformed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'additionalTest': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  tumourboards: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'dateOfMolecularTumorBoard': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'typeOfSampleAnalyzed': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'typeOfTumourSampleAnalyzed': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'analysesDiscussed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'somaticSampleType': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'normalExpressionComparator': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'diseaseExpressionComparator': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'hasAGermlineVariantBeenIdentifiedByProfilingThatMayPredisposeToCancer': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'actionableTargetFound': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'molecularTumorBoardRecommendation': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'germlineDnaSampleId': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'tumorDnaSampleId': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'tumorRnaSampleId': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'germlineSnvDiscussed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'somaticSnvDiscussed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'cnvsDiscussed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'structuralVariantDiscussed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'classificationOfVariants': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'clinicalValidationProgress': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'typeOfValidation': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'agentOrDrugClass': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'levelOfEvidenceForExpressionTargetAgentMatch': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'didTreatmentPlanChangeBasedOnProfilingResult': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'howTreatmentHasAlteredBasedOnProfiling': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'reasonTreatmentPlanDidNotChangeBasedOnProfiling': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'detailsOfTreatmentPlanImpact': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'patientOrFamilyInformedOfGermlineVariant': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'patientHasBeenReferredToAHereditaryCancerProgramBasedOnThisMolecularProfiling': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'summaryReport': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'actionableExpressionOutlier': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'actionableGermlineVariant': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'germlineVariantsDrug': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'germlineVariantsDrugClass': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'germlineVariantsDiscussed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'actionableSomaticVariants': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'somaticVariantsDrug': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'somaticVariantsDrugClass': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'somaticVariantsDiscussed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'anyActionableExpressionOutlier': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'expressionDrug': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'expressionDrugClass': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'expressionTypeOfAnalysisUsed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'expressionTypeOfInformationUtility': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'expressionAlteredGene': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'expressionNonActionableGene': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'expressionTypeOfAlteration': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'anyActionableGermlineVariants': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'germlineVariantsTypeOfAnalysisUsed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'germlineVariantsClassificationOfVariants': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'germlineVariantsTypeOfInformationUtility': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'anyActionableSomaticVariants': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'somaticVariantsTypeOfAnalysisUsed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'somaticVariantsTypeOfInformationUtility': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'somaticVariantsNonActionable': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  outcomes: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'physicalExamId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'dateOfAssessment': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'diseaseResponseOrStatus': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'otherResponseClassification': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'minimalResidualDiseaseAssessment': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'methodOfResponseEvaluation': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'responseCriteriaUsed': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'summaryStage': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'sitesOfAnyProgressionOrRecurrence': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'vitalStatus': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'height': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'weight': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': false},
    'heightUnits': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'weightUnits': {'Filter':SelectColumnFilter, 'active': true, 'hidden': false},
    'performanceStatus': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'overallSurvivalInMonths': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'diseaseFreeSurvivalInMonths': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'siteOfRelapseOrProgression': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'intervalProgressionOrRecurrence': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'intervalRegressionOrDecreaseInDisease': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'levelOfMalignancy': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'treatmentInducedNeoplasmSite': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'dateOfDiagnosisOfTreatmentInducedNeoplasm': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  complications: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'date': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'lateComplicationOfTherapyDeveloped': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'lateToxicityDetail': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'suspectedTreatmentInducedNeoplasmDeveloped': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'treatmentInducedNeoplasmDetails': {'Filter':DefaultColumnFilter, 'true': false, 'hidden': true},
  },
  consents: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'consentId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'consentDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'consentVersion': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'patientConsentedTo': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'reasonForRejection': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'wasAssentObtained': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'dateOfAssent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'assentFormVersion': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'ifAssentNotObtainedWhyNot': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'reconsentDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'reconsentVersion': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'consentingCoordinatorName': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'previouslyConsented': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'nameOfOtherBiobank': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'hasConsentBeenWithdrawn': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'dateOfConsentWithdrawal': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'typeOfConsentWithdrawal': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'reasonForConsentWithdrawal': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'consentFormComplete': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  chemotherapies: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'startDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'doseFrequency': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'numberOfCycle': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'treatingCentreName': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'doseUnit': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'treatmentIntent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'route': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'protocolCode': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'stopDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'dose': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'daysPerCycle': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'type': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'recordingDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'courseNumber': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'systematicTherapyAgentName': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  radiotherapies: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'radiationSite': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'siteNumber': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'startDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'adjacentFractions': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'radiationType': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'boostDose': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'testResult': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'startIntervalRadRaw': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'adjacentFields': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'baseline': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'technique': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'stopDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'courseNumber': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'brachytherapyDose': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'testResultStd': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'complete': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'boostSite': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'treatedRegion': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'startIntervalRad': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'treatingCentreName': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'totalDose': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'therapeuticModality': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'recordingDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'radiotherapyDose': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  immunotherapies: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'startDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'immunotherapyType': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'immunotherapyTarget': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'immunotherapyDetail': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'courseNumber': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  surgeries: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'collectionTimePoint': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'startDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'site': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'diagnosisDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'type': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'stopDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'recordingDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'courseNumber': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  celltransplants: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'treatmentPlanId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'startDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true}, 
    'cellSource': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true}, 
    'courseNumber': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true}, 
    'donorType': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  slides: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'sampleId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'slideId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'slideOtherId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'tumorNucleiPercent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'inflammatoryInfiltrationPercent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'necrosisPercent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'neutrophilInfiltrationPercent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'proliferatingCellsNumber': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'monocyteInfiltrationPercent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'lymphocyteInfiltrationPercent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'eosinophilInfiltrationPercent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'tumorCellsPercent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'stromalCellsPercent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'normalCellsPercent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'sectionLocation': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'granulocyteInfiltrationPercent': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  studies: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'status': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true}, 
    'startDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true}, 
    'recordingDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true}, 
    'endDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
  labtests: {
    'id': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'datasetId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'name': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'patientId': {'Filter':DefaultColumnFilter, 'active': false, 'hidden': true},
    'startDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'endDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'testResults': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'collectionDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'recordingDate': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'eventType': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
    'timePoint': {'Filter':DefaultColumnFilter, 'active': true, 'hidden': true},
  },
};


export default tableSchema